version: '3'
services:
  dbmysql:
    image: mysql:5.7
    restart: always
    networks:
      - kafka-local
    environment:
      MYSQL_DATABASE: 'db_payment'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql

  app:
    build: .
    ports:
      - "8010"
    networks:
      - kafka-local
    depends_on:
      - dbmysql
      - kafka-server
    environment:
#      WAIT_HOSTS: dbmysql:3307
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/db_payment?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    links:
      - dbmysql
      - kafka-server

  kafka-server:
    build: kafka
    networks:
      - kafka-local
    hostname: kafka-server
    environment:
      - ADVERTISED_HOST=127.0.0.1
      - NUM_PARTITIONS=10
    ports:
      - "2181:2181"
      - "9092:9092" 

# Names our volume
volumes:
  my-db:


networks:
  kafka-local:
